--
CREATE OR REPLACE DIRECTORY SAMPLE_DATA as '%HOL_ROOT%/SampleData'
/
DROP TABLE CITY_LOTS_EXTERNAL
/
DROP TABLE CITY_LOT_FEATURES
/
CREATE TABLE CITY_LOTS_EXTERNAL(
  JSON_DOCUMENT CLOB
)
ORGANIZATION EXTERNAL(
   TYPE ORACLE_LOADER
   DEFAULT DIRECTORY SAMPLE_DATA
   ACCESS PARAMETERS (
      RECORDS DELIMITED BY 0x'0A'
      READSIZE 256000000
      DISABLE_DIRECTORY_LINK_CHECK  
      BADFILE SAMPLE_DATA: 'CITY_LOTS_EXTERNAL.bad'
      LOGFILE SAMPLE_DATA: 'CITY_LOTS_EXTERNAL.log'
      FIELDS(
        JSON_DOCUMENT CHAR(1024000)
      ) 
   )
   LOCATION (
     SAMPLE_DATA:'citylots.json.dmp'
   )
)
PARALLEL
REJECT LIMIT UNLIMITED
/
create table CITY_LOT_FEATURES
as
select JSON_DOCUMENT as FEATURE
  from CITY_LOTS_EXTERNAL
/
commit
/
select count(*) 
  from CITY_LOT_FEATURES
/
